mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('pmcircle/', include("pmcircle.urls", namespace="pmcircle")),
]

mysite/pmcircle/urls.py
from django.urls import path
from . import views

app_name = 'pmcircle'

urlpatterns = [
    path('', views.PmCircle.as_view(), name="pmcircle"),
]

mysite/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

mysite/pmcircle/models.py
from django.db import models

# Create your models here.

mysite/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

mysite/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

mysite/mysite/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

mysite/pmcircle/views.py
from django.views.generic import TemplateView

# Create your views here.
class PmCircle(TemplateView):
    template_name = "pmcircle/pmcircle.html"

mysite/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block account %}
<div class="container">
  <h4>Login</h4>
  <form method="POST" class="form">
    {% csrf_token %}
    {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Login</button>
  </form>
</div>
{% endblock %}

mysite/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block account %}
 <div class="container">
  <h4>Sign Up</h4>
  <form method="POST" class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>

</div>

{% endblock %}

mysite/pmcircle/templates/pmcircle/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'mysite/css/final.css' %}"> -->
    <link rel="stylesheet" href="{% static 'pmcircle/css/pmcircle.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Kalam" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <title id="nam">PM Interaction</title>
  </head>
  <!--close of head  -->
  <!--##############################################  -->
  <body>
    <header>
    <nav id="navbar" class="navbar navbar-expand-lg ">
      <a href="{% url 'home' %}" class="navbar-brand px-4 py-2"><strong>designCalc</strong> <span id="sol"></span> </a>
      <button  class="navbar-toggler" type="button"  data-toggle="collapse" data-target="#myNavbar">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item"><a href="#header" class="nav-link m-2 text-capitalize">Home</a></li>
          <li class="nav-item"><a href="#skills" class="nav-link m-2 text-capitalize">Help</a></li>
          <li class="nav-item"><a href="#about" class="nav-link m-2 text-capitalize">Q&A</a></li>
          <li class="nav-item dropdown mt-2">
           <a class="nav-link dropdown-toggle text-capitalize" href="#applications"   id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Applications</a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item" href="#">Bearing Design</a>
             <a class="dropdown-item" href="#" data-target="#pmmodal" data-toggle="modal">Pm Curve</a>
             <a class="dropdown-item" href="#">Bridge Info</a>
           </div>
         </li>
          <li class="nav-item"><a href="#posts" class="nav-link m-2 text-capitalize">Blogs</a></li>
          <li class="nav-item"><a href="#reviews" class="nav-link m-2 text-capitalize">Reviews</a>
    </ul>
    <!--######################## login signup logout right #######################-->
<ul class="nav navbar-nav navbar-right  ">
  {% if user.is_authenticated %}
  <li class=""><a href="#" class="nav-link m-2">hi {{user.username}}</a></li>
  <li class=""><a href="{% url 'accounts:logout' %}" class="nav-link m-2 text-capitalize">Logout</a></li>
  {% else %}
  <li class=""><a href="{% url 'accounts:login' %}" class="nav-link m-2 text-capitalize">Login</a></li>
  <li class=""><a href="{% url 'accounts:signup' %}" class="nav-link m-2 text-capitalize">Sign Up</a></li>
  {% endif %}
</ul>
  </div>
</nav>
<!-- ############################################end of navbar##################################33 -->
<div class="topcorner">
  <button type="button" name="" class="btn d-print-none" onclick="window.print();"> <span><i class="fas fa-print"></i></span> Print</button>
</div>
</header>

{% block content %}
{% endblock %}


 <!-- Footer -->
<footer class="page-footer font-small pt-4">
      <hr>
       <div class="row d-flex align-items-center">
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8">
          <!--Copyright-->
          <p class="text-center text-md-left">© 2018 Copyright:
            <a href="#">
              <strong> designCalc</strong>
            </a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0">

          <!-- Social buttons -->
          <div class="text-center text-md-right">
            <ul class="list-unstyled list-inline">
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-google-plus"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

     </div>
    <!-- Footer Links -->

  </footer>
  <!-- Footer -->

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.2.2/d3.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://unpkg.com/tippy.js@2.5.4/dist/tippy.all.min.js"></script>

  </body>

  <!-- <script src="script.js"></script> -->
  <script src="{% static "mysite/js/script.js"%}" type="text/javascript" ></script>
  <script src="{% static "pmcircle/js/util2.js"%}" type="text/javascript" ></script>
  <script src="{% static "pmcircle/js/circle.js"%}" type="text/javascript" ></script>
  <script src="{% static "pmcircle/js/cirCurve.js"%}" type="text/javascript" ></script>
  <script src="{% static "pmcircle/js/interpolate.js"%}" type="text/javascript" ></script>

</html>

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'mysite/css/final.css' %}">
    <!-- <link rel="stylesheet" href="main.css"> -->

    <link href="https://fonts.googleapis.com/css?family=Kalam" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <title id="nam">Design Calc solutions</title>
  </head>
  <!--close of head  -->
  <!--##############################################  -->
  <body>
    <header>
    <nav id="navbar" class="navbar navbar-expand-lg ">
      <a href="{% url 'home' %}" class="navbar-brand px-4 py-2"><strong>designCalc</strong> <span id="sol"></span> </a>
      <button  class="navbar-toggler" type="button"  data-toggle="collapse" data-target="#myNavbar">
        <div class="bar1"></div>
        <div class="bar2"></div>
        <div class="bar3"></div>
      </button>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item"><a href="#header" class="nav-link m-2 text-capitalize">Home</a></li>
          <li class="nav-item"><a href="#skills" class="nav-link m-2 text-capitalize">Help</a></li>
          <li class="nav-item"><a href="#about" class="nav-link m-2 text-capitalize">Q&A</a></li>
          <li class="nav-item dropdown mt-2">
           <a class="nav-link dropdown-toggle text-capitalize" href="#applications"   id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Applications</a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
             <a class="dropdown-item" href="#">Bearing Design</a>
             <a class="dropdown-item" href="#" data-target="#pmmodal" data-toggle="modal">Pm Curve</a>
             <a class="dropdown-item" href="#">Bridge Info</a>
           </div>
         </li>
          <li class="nav-item"><a href="#posts" class="nav-link m-2 text-capitalize">Blogs</a></li>
          <li class="nav-item"><a href="#reviews" class="nav-link m-2 text-capitalize">Reviews</a>
    </ul>
    <!--######################## login signup logout right #######################-->
<ul class="nav navbar-nav navbar-right  ">
  {% if user.is_authenticated %}
  <li class=""><a href="#" class="nav-link m-2">hi {{user.username}}</a></li>
  <li class=""><a href="{% url 'accounts:logout' %}" class="nav-link m-2 text-capitalize">Logout</a></li>
  {% else %}
  <li class=""><a href="{% url 'accounts:login' %}" class="nav-link m-2 text-capitalize">Login</a></li>
  <li class=""><a href="{% url 'accounts:signup' %}" class="nav-link m-2 text-capitalize">Sign Up</a></li>
  {% endif %}
</ul>
  </div>
</nav>
<!-- ############################################end of navbar##################################33 -->

{% block slider %}
{% endblock %}

</header>

{% block account %}
{% endblock %}

{% block card %}
{% endblock %}


 <!-- Footer -->
<footer class="page-footer font-small mt-5 pt-4">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
      <!-- Footer links -->
      <div class="row text-center text-md-left mt-3 pb-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Design Calc</h6>
          <p class="p">Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur
            adipisicing elit.</p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p class="p">
            <a  class="p"href="#!">Bearing</a>
          </p>
          <p class="p">
            <a  class="p"href="#!">Pm curve</a>
          </p>
          <p class="p">
            <a class="p" href="#!">calculator</a>
          </p>
          <p class="p">
            <a  class="p"href="#!">structural</a>
          </p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
          <p class="p">
            <a class="p" href="#!">Your Account</a>
          </p>
          <p class="p">
            <a  class="p"href="#!">Pricing</a>
          </p>
          <p class="p">
            <a class="p" href="#!">Help</a>
          </p>
          <p class="p">
            <a class="p" href="#!">Email Subscribehere</a>
          </p>
        </div>
        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p class="p">
            <i class="fa fa-home mr-3"></i> Chicago, IL 60640, US</p>
          <p class="p">
            <i class="fa fa-envelope mr-3"></i> info@gmail.com</p>
          <p class="p">
            <i class="fa fa-phone mr-3"></i> + 01 312 623 5291</p>
          <p class="p">
            <i class="fa fa-print mr-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Footer links -->
      <hr>
      <!-- Grid row -->
      <div class="row d-flex align-items-center">
        <!-- Grid column -->
        <div class="col-md-7 col-lg-8">
          <!--Copyright-->
          <p class="text-center text-md-left">© 2018 Copyright:
            <a href="#">
              <strong> design Cal.com</strong>
            </a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0">

          <!-- Social buttons -->
          <div class="text-center text-md-right">
            <ul class="list-unstyled list-inline">
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-google-plus"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

  </footer>
  <!-- Footer -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  </body>

  <!-- <script src="script.js"></script> -->
  <script src="{% static "mysite/js/script.js"%}" type="text/javascript" ></script>
</html>

mysite/templates/index.html
{% extends "base.html"%}
<!-- {% load static %} -->
{% block slider %}
<div class="container-fluid mt-0">
  <div class="row">
    <div class="col no-padding">
      <div id="demo-slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item item-1 active" style="background-image: url({% static 'mysite/img/slider-1.jpg' %})">
            <div class="carousel-caption mb-5 text-right">
              <h1 class=" my-auto text-center"> Design cal helps for rapid calculations</h1>
            </div>
          </div>
          <div class="carousel-item item-2" style="background-image: url({% static 'mysite/img/slider-2.jpg' %})">
        </div>
        <a class="carousel-control-prev" href="#demo-slider" role="button" data-slide="prev">
<span class="carousel-control-prev-icon"></span>
<span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#demo-slider" role="button" data-slide="next">
<span class="carousel-control-next-icon"></span>
<span class="sr-only">Next</span></a>
      </div>
    </div>
  </div>
 </div>
</div>
{% endblock %}

{% block card %}
<!-- ###################card start -->
  <div class="container">
    <!--**************title************************-->
    <div class="row title mt-2 mb-0">
      <div class="col text-center">
        <h1 id= "heading" class="text-uppercase mb-0">Applications</h1>
        <a href="#" class="mb-0"><i class="fas fa-globe"></i></a>
        <div class="title-underline "></div>
      </div>
    </div>
    <!--     ************* end of title***************-->
    <div class="card-deck mt-4">
      <div class="card mx-4">
        <img class="card-img-top" src="{% static 'mysite/img/PMcurve.jpg' %}" alt="card image">
        <div class="card-body">
          <h5 class="card-title font-weight-bold text-capitalize">Pm Curve Application</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          <a href="#" class="btn btn-primary card1" data-target="#pmmodal" data-toggle="modal">Click Here</a>
         <!-- <a href="#" data-target="#pmmodal" data-toggle="modal"></a> -->
    </div>
  </div>
  <div class="card mx-4">
    <img class="card-img-top" src="{% static 'mysite/img/bearing.png' %}" alt="card image">
    <div class="card-body">
      <h5 class="card-title text-capitalize font-weight-bold">Bearing Design Application</h5>

      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
       <a href="http://zpkumar.pythonanywhere.com/bearing18.html" class="btn btn-primary card1" >Click Here</a>
    </div>
  </div>
  <div class="card mx-4">
    <img class="card-img-top" src="{% static 'mysite/img/app1.JPG' %}" alt="card image">
    <div class="card-body">
      <h5 class="card-title  text-capitalize font-weight-bold">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      <!-- <a href="#" class="btn btn-primary card1 ">Click Here</a> -->
      <a href="#"></a>
    </div>
  </div>
</div>
</div>
<!-- ###################card end -->
<!-- pm curve modal -->
<div class="modal" id="pmmodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Pm curve applications</h4>
        <!-- <button type="close" name="button" class="close" data-dismiss="modal">&times;</button> -->
        <button type="close" name="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="card-deck mt-4">
      <div class="card">
        <img class="card-img-top" src="{% static 'mysite/img/pmcircle.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Pm Curve Application</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
           <a href="{% url 'pmcircle:pmcircle' %}" class="btn btn-primary">Click Here</a>
        </div>
      </div>
      <div class="card">
        <img class="card-img-top" src="{% static 'mysite/img/pmcircle.jpg' %}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Bearing Design Application</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
          <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          <a href="#" class="btn btn-primary">Click Here</a>
        </div>
      </div>
    </div>
          <div class="modal-footer">
             <button type="close" class="btn btn-primary" data-dismiss="modal">Close</button>
          </div>
      </div>
    </div>
  </div>
</div>
<!--###########################################################end of pm model#########################  -->
{% endblock %}